apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  type: NodePort
  selector:
    app: medicure
  ports:
    - port: 8082         # ClusterIP port
      targetPort: 8082   # app running inside container
      nodePort: 30081    # public NodePort

